console.log('Process Architecture ',process.arch)
console.log('Process Id is ',process.pid)
console.log('Process Environment ',process.pid)
console.log('process platform ',process.platform)
console.log('process version',process.version)
console.log('process release',process.release)